{
 "title": "goi_dash",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu)(irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "/dev/sda2" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "total" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "free" }
   ]
  },
  {
   "title": "CPULA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPULA 1" },
    { "expr": "node_load5", "legendFormat": "CPULA 5" },
    { "expr": "node_load15", "legendFormat": "CPULA 15" }
   ]
  }
 ]
}