---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse

# Vector RUN------------------------------------------------

- name: Install Vector
  hosts: vector
  roles:
    - role: vector-role

# Lighthouse RUN------------------------------------------------

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  handlers:                             # Объявление списка handlers для перезапуска сервиса Nginx
    - name: Start nginx service
      ansible.builtin.service:
        name: nginx
        enabled: "yes"
        state: restarted
  tasks:
    - name: Install Nginx               # Устанавливаем Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
      notify: Start nginx service
    - name: Nginx config
      ansible.builtin.template:
        src: templates/nginx.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: '644'
    - name: Install Git                 # Устанавливаем Git
      ansible.builtin.apt:
        name: "git"

  roles:
    - role: lighthouse-role