---

- name: Verify
  hosts: all
  gather_facts: false

  vars:
    vector_config_path: /etc/vector/vector.yaml
  tasks:
    - name: Get Vector version
      ansible.builtin.command: "vector --version"
      changed_when: false
      register: vector_version
    - name: Assert Vector instalation
      ansible.builtin.assert:
        that: "'{{ vector_version.rc }}' == '0'"
