#version: "3.9"

services:
  elasticsearch-hot:
    image: elasticsearch:8.11.3
    container_name: elasticsearch-hot
    environment:
      - node.name=elasticsearch-hot
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-hot,elasticsearch-warm
      - cluster.initial_master_nodes=elasticsearch-hot,elasticsearch-warm
      - node.roles=master,data_content,data_hot  
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - xpack.security.enabled=false
    volumes:
      #- ./elasticsearch/01/config/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      #- ./elasticsearch/01/data:/usr/share/elasticsearch/data
      - data01:/usr/share/elasticsearch/data:Z
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch-warm

  elasticsearch-warm:
    image: elasticsearch:8.11.3
    container_name: elasticsearch-warm
    environment:
      - node.name=elasticsearch-warm
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-hot,elasticsearch-warm
      - cluster.initial_master_nodes=elasticsearch-hot,elasticsearch-warm
      - node.roles=master,data_warm
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - "http.host=0.0.0.0"
    volumes:
      #- ./elasticsearch/02/config/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      #- ./elasticsearch/02/data:/usr/share/elasticsearch/data
      - data02:/usr/share/elasticsearch/data:Z
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elastic

  logstash:
    image: logstash:8.11.3
    container_name: logstash
    volumes:
      - ./logstash/config.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    networks:
      - elastic
    depends_on:
      - elasticsearch-hot

  kibana:
    image: kibana:8.11.3
    container_name: kibana
    depends_on:
      - elasticsearch-hot
    volumes:
      - ./kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elastic
    ports:
      - "5601:5601"

  filebeat:
    image: elastic/filebeat:8.11.4
    container_name: filebeat
    privileged: true
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/config.yml:/usr/share/filebeat/filebeat.yml:Z
      - /var/lib/docker:/var/lib/docker:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
    depends_on:
      - logstash
    networks:
      - elastic

  application:
    image: library/python:3.9-alpine
    container_name: application
    volumes:
      - ./pinger/:/opt/:Z
    entrypoint: python3 /opt/run.py
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
